# Generated by Django 5.0.6 on 2024-06-28 08:17

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=300, verbose_name="место")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="время")),
                ("action", models.CharField(max_length=300, verbose_name="действие")),
                (
                    "nice_habit",
                    models.BooleanField(
                        default=False, verbose_name="признак приятной привычки"
                    ),
                ),
                (
                    "period",
                    models.IntegerField(
                        choices=[
                            (1, "раз в день"),
                            (2, "раз в 2 дня"),
                            (3, "раз в 3 дня"),
                            (4, "раз в 4 дня"),
                            (5, "раз в 5 дня"),
                            (6, "раз в 6 дня"),
                            (7, "раз в неделю"),
                        ],
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="вознаграждение",
                    ),
                ),
                (
                    "time_execution",
                    models.DurationField(
                        default=datetime.timedelta(seconds=120),
                        verbose_name="время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="публичная"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="владелец",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habits.habit",
                        verbose_name="связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
