# Generated by Django 5.0.6 on 2024-06-26 11:21

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("place", models.CharField(max_length=300, verbose_name="место")),
                ("time", models.TimeField(blank=True, null=True, verbose_name="время")),
                ("action", models.CharField(max_length=300, verbose_name="действие")),
                (
                    "nice_habit",
                    models.BooleanField(
                        default=False, verbose_name="признак приятной привычки"
                    ),
                ),
                (
                    "period",
                    models.IntegerField(
                        choices=[
                            ("раз в день", "раз в день"),
                            ("раз в 2 дня", "раз в 2 дня"),
                            ("раз в 3 дня", "раз в 3 дня"),
                            ("раз в 4 дня", "раз в 4 дня"),
                            ("раз в 5 дня", "раз в 5 дня"),
                            ("раз в 6 дня", "раз в 6 дня"),
                            ("раз в неделю", "раз в неделю"),
                        ],
                        default="раз в день",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="вознаграждение",
                    ),
                ),
                (
                    "time_execution",
                    models.IntegerField(
                        default=datetime.timedelta(seconds=120),
                        verbose_name="время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="публичная"),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
