# Generated by Django 5.0.6 on 2024-06-27 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.IntegerField(
                choices=[
                    (1, "раз в день"),
                    (2, "раз в 2 дня"),
                    (3, "раз в 3 дня"),
                    (4, "раз в 4 дня"),
                    (5, "раз в 5 дня"),
                    (6, "раз в 6 дня"),
                    (7, "раз в неделю"),
                ],
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7),
                ],
                verbose_name="периодичность",
            ),
        ),
    ]
